Blocks activity section
CONUN-Global/conscan-explorer-v2 pull request #16
Opened 2021-08-20 04:25 UTC by JM066

2021-08-20 05:07 UTC, ivanms1 requested changes

2021-08-20 05:07 UTC, ivanms1 commented on src/components/Layout/PageContainer/BlocksActivitySection/BlocksActivitySection.module.scss
> +  // flex: 1 1 400px;
remove

2021-08-20 05:07 UTC, ivanms1 commented on src/components/Layout/PageContainer/BlocksActivitySection/index.tsx
> +interface Block {
spacing and import order

2021-08-20 05:07 UTC, ivanms1 commented on src/components/Layout/PageContainer/BlocksActivitySection/index.tsx
> +        Cell: function Celly({ value }: { value: any }) {
more meaningful function name instead of `Celly`

2021-08-20 05:07 UTC, ivanms1 commented on src/components/Layout/PageContainer/BlocksActivitySection/index.tsx
> +        Cell: function Celly({ value }: { value: number }) {
```suggestion
        Cell: function TxCount({ value }: { value: number }) {
```

2021-08-20 05:07 UTC, ivanms1 commented on src/components/Table/index.tsx
> +                  return column.hideHeader === true ? null : (
```suggestion
                  return column.hideHeader ? null : (
```

2021-08-20 05:07 UTC, ivanms1 commented on src/pages/Main/index.tsx
> +import BlocksActivitySection from "@/components/Layout/PageContainer/BlocksActivitySection";
import order

2021-08-20 06:17 UTC, JM066 commented on src/pages/Main/index.tsx
> +import BlocksActivitySection from "@/components/Layout/PageContainer/BlocksActivitySection";
Pages come after compoents?

2021-08-20 06:50 UTC, ivanms1 commented on src/pages/Main/index.tsx
> +import BlocksActivitySection from "@/components/Layout/PageContainer/BlocksActivitySection";
wait, mm sorry just put them together

2021-08-23 05:42 UTC, BruceJi7 commented on src/hooks/useBlockActivityData.tsx
> +    const response = await instance.get(`/${blockProp}/${channelHash}`);
I think it'd be better to just put blockActivity there as a string instead of as a prop.

2021-08-23 05:42 UTC, BruceJi7 commented on src/helpers/getDistance.ts
> +export function getDistance(datePast: string) {
can we name this getTimeDistance or getTimeAgo or something? That would be a bit more clear

2021-08-23 05:47 UTC, BruceJi7 requested changes
Can you put the blockActivity url string into the hook plis?
Also it'd be good to call the getDistance something else that makes it clear it's about time :O

2021-08-23 07:49 UTC, BruceJi7 approved these changes

2021-08-23 07:53 UTC, ivanms1 approved these changes

2021-08-23 08:18 UTC, merged